### ISSUE TITLE
Permissions to push a new branch

### ISSUE THREAD

**Issue by njvitto** [roNn23/coinmarketcap-historical-data-crawler#1]
Hi @roNn23 I have just ready a new branch where I added the possibility to set a timeout (must have to run the script because of the limits of CMC) and some other minor improvements.

Can you please give me the permission? :)

Thx!

**Comment by roNn23** [comment]
Hey @njvitto!
What permission do you want? Just use a `Pull request` and I will check your work.
Thanks!

**Comment by njvitto** [comment]
@roNn23  I can't push a new branch (I receive an error from github on your repo while I am able to push branches on my private repos) so I'm not able to make a pull request unfortunately :-)
I don't have any public repository but maybe you need to enable something or add me as a user with permissions to push branches. Thanks!

**Comment by roNn23** [comment]
@njvitto You just have to fork this repo, edit your changes and then make the pull request.
https://help.github.com/en/articles/creating-a-pull-request-from-a-fork
